import { describe, it, expect } from "vitest";
import bcrypt from "bcryptjs";

/**
 * Direct bcryptjs round-trip tests.
 *
 * This is a thin safety net around the two bcryptjs APIs the codebase
 * actually uses:
 *   - bcrypt.hash(plain, rounds)   — register, reset-password, profile
 *   - bcrypt.compare(plain, hash)  — login, profile password verification
 *
 * The real purpose of this file is to catch regressions when bcryptjs
 * is upgraded across major versions. The 2.x → 3.x bump notably switched
 * the default module format to ESM with a UMD fallback, switched the
 * default hash prefix from `$2a$` to `$2b$`, and started shipping
 * native TypeScript types (replacing @types/bcryptjs). This suite
 * fails loudly if any of those changes break the default-import path,
 * the hash shape, or the compare logic.
 */

describe("bcryptjs round-trip", () => {
  it("hashes a password and verifies it", async () => {
    const plain = "correct-horse-battery-staple";
    const hash = await bcrypt.hash(plain, 10);
    expect(await bcrypt.compare(plain, hash)).toBe(true);
  });

  it("rejects the wrong password", async () => {
    const hash = await bcrypt.hash("right-password", 10);
    expect(await bcrypt.compare("wrong-password", hash)).toBe(false);
  });

  it("produces a different salt on every call", async () => {
    const h1 = await bcrypt.hash("pw", 10);
    const h2 = await bcrypt.hash("pw", 10);
    expect(h1).not.toBe(h2);
    // Both still verify against the original plaintext.
    expect(await bcrypt.compare("pw", h1)).toBe(true);
    expect(await bcrypt.compare("pw", h2)).toBe(true);
  });

  it("produces a hash in the standard modular crypt format", async () => {
    const hash = await bcrypt.hash("any", 10);
    // Either 2a, 2b, or 2y prefix — all are bcrypt variants that
    // comparison will accept. Cost is a 2-digit decimal.
    expect(hash).toMatch(/^\$2[aby]\$\d{2}\$/);
  });

  it("respects the cost parameter (fingerprint in the hash)", async () => {
    const cheap = await bcrypt.hash("pw", 4);
    expect(cheap).toMatch(/^\$2[aby]\$04\$/);
    const expensive = await bcrypt.hash("pw", 10);
    expect(expensive).toMatch(/^\$2[aby]\$10\$/);
  });

  it("still verifies $2a$ hashes from the OpenWall test vectors", async () => {
    // If the 3.x compare function rejected older variants, every
    // existing user in the database (whose hashes were generated by
    // bcryptjs 2.x with its `$2a$` default) would be unable to log
    // in — so this is the single most important regression check
    // in the file.
    //
    // These hashes are the canonical reference vectors from the
    // OpenWall crypt_blowfish distribution (wrapper.c), published
    // by the bcrypt reference implementation. They are guaranteed
    // to be valid bcrypt output regardless of which library
    // generated them.
    //   https://www.openwall.com/crypt/
    const vectors: Array<{ plain: string; hash: string }> = [
      {
        plain: "U*U",
        hash: "$2a$05$CCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW",
      },
      {
        plain: "U*U*",
        hash: "$2a$05$CCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK",
      },
      {
        plain: "U*U*U",
        hash: "$2a$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a",
      },
    ];
    for (const { plain, hash } of vectors) {
      expect(await bcrypt.compare(plain, hash)).toBe(true);
      expect(await bcrypt.compare(plain + "x", hash)).toBe(false);
    }
  });

  it("generates $2b$ hashes by default (bcryptjs 3 behavior)", async () => {
    // bcryptjs 3.x switched the default hash prefix from `$2a$` to
    // `$2b$` (RFC-compliant bcrypt). Existing stored hashes are still
    // accepted — see the OpenWall vectors test above — but newly
    // generated hashes will now be `$2b$`. This test pins the
    // default so a future regression (e.g. a downgrade to 2.x) would
    // show up as a bright red line rather than a silent behavior
    // change in production hash storage.
    const hash = await bcrypt.hash("any", 4);
    expect(hash).toMatch(/^\$2b\$04\$/);
    expect(await bcrypt.compare("any", hash)).toBe(true);
  });
});
